### ISSUE TITLE
OS X Compatibility: passthrough.c

### ISSUE THREAD

**Issue by salmanarif** [HPCE/hpce-2014-cw2#15] opened 2015-02-02 20:55 UTC
A note for OS X users:

`passthrough.c` seems to break down after buffer size of 32 (64 bytes), with the following error:
`Did not receive expected number of bytes.`

The same code runs fine on Linux. I'm not sure what is causing this, but I wonder if this will have an effect on other parts of the Coursework.

**Comment by txsl** [comment] 2015-02-02 20:59
I installed GCC 4.8 via homebrew (see [Apple Stack Exchange](http://apple.stackexchange.com/questions/38222/how-do-i-install-gcc-via-homebrew)), and whilst it does build, it exhibits the same behaviour.

**Comment by iassael** [comment] 2015-02-02 21:04
With gcc49 from homebrew everything worked fine on Yosemite.
Try `brew install gcc49`
(ps. maybe you have to tap the new repository running: `brew tap homebrew/versions`)

**Comment by threewholefish** [comment] 2015-02-03 15:00
Ubuntu 12.04, same problem. It seems to be related to the amount of data you pass in. using gcc 4.6.3

**Comment by salmanarif** [comment] 2015-02-03 16:09
Using `gcc49` does not appear to help on OS X.

**Comment by txsl** [comment] 2015-02-03 19:56
@iassael - `gcc49` doesn't work for me either.
@schmethan - can you be more specific as to what you think the problem is?

I've added another fprintf statement when it exits, and found something interesting:

> 16
> Processing 16 stereo samples at a time
> 
> 32
> Processing 32 stereo samples at a time
> ./passthrough : Did not receive expected number of bytes.
> Instead got 64, but expected 128...
> 
> 64
> Processing 64 stereo samples at a time
> ./passthrough : Did not receive expected number of bytes.
> Instead got 64, but expected 256...
> 
> 128
> Processing 128 stereo samples at a time
> ./passthrough : Did not receive expected number of bytes.
> Instead got 64, but expected 512...
> 
> 256
> Processing 256 stereo samples at a time
> ./passthrough : Did not receive expected number of bytes.
> Instead got 576, but expected 1024...
> 
> 512
> Processing 512 stereo samples at a time
> ./passthrough : Did not receive expected number of bytes.
> Instead got 576, but expected 2048...
> 
> 1024
> Processing 1024 stereo samples at a time
> ./passthrough : Did not receive expected number of bytes.
> Instead got 576, but expected 4096...

So it seems to hit some sort of _limit__(dare I call it a blockage somewhere?!). But before the value of 576, it also seems to get stuck at 64. I do wonder what is happening.

**Comment by kronocharia** [comment] 2015-02-03 23:21
If I change 1M to a power of 2, its resolved, ie 1048576

```
    }else if(got!=cbBuffer){
        fprintf(stderr, "%s : Did not receive expected number of bytes.\n", argv[0]);
        exit(1);
    }
```

it gets stuck in this else if part, and the issue is got is like 256 whereas cbBuffer is 2048 or whatever

Are we meant to modify passthrough to handle this properly? Or just adjust the input size :P

**Comment by txsl** [comment] 2015-02-04 10:00
So I was thinking about this last night... @kronocharia you're right

When we say we want to take in n samples, this means we want 4n bytes (because 2 channels \* 2 bytes (16 bits)).

So for example, `cat /dev/zero | head -c 14 | ./passthrough 4 > /dev/null` will fail with the response

> Processing 4 stereo samples at a time
> ./passthrough : Did not receive expected number of bytes.
> Instead got 14, but expected 16...

And if you think about passing in 1000000 bytes, `1000000 % (1024*4) = 576`, and `1000000 % (128*4) = 64` - all . It's the _overflow_ of the last set of bytes which aren't the full length of the buffer.

Modifying the `else if` statement seems sensible as otherwise all data will need to be of the correct length.

Last curious thought: why does this happen on some machines and not others? Surely this should be a consistent error? Unless different compilers treat size behaviour differently? (although I would hope this would be a very reproducible error!)

**Comment by threewholefish** [comment] 2015-02-04 10:25
it may not be different machines, but different implementations of
passthrough?

**Comment by m8pple** [comment] 2015-02-04 10:31
Sorry, bit behind on this, but it looks like there is a good discussion anyway. It looks like certain
OSs are doing something with the behaviour of [read](http://linux.die.net/man/2/read). It
is not _required_ to return the number of bytes requested, it may return less, but in my
experience most OSs will do a blocking read on stdin (though they aren't required to AFAICT).

So I haven't seen errors before in the middle of the stream, but where there is (inevitably)
a problem is on the end of stream as @txsl points out: if you read in chunks of 64 samples,
and there are 100 samples, then the final read will get less that it asked for.

I'm only concentrating on the steady state processing, so my test code will accept whatever
end of stream stuff you do. If it returns less than you requested in the _middle_ of the
stream though, that is more of a problem. Can someone confirm which version is
happening?

**Comment by kronocharia** [comment] 2015-02-04 11:51
As far as I can tell, it's only doing it to the last sample, although I didn't count the number of processed samples to make sure they add up... so bottom line, we can ignore the warning message if this is the case?

**Comment by m8pple** [comment] 2015-02-04 12:59
Yes, that is correct - to be polite to the user it would be good to terminate without a warning
when everything seems to be normal, but it's certainly not a requirement.

Receiving something that is not a multiple of four bytes would arguably be an error condition,
but I don't want to overcomplicate things.

**Comment by darioml** [comment] 2015-02-04 19:28
Maybe update README.md to reflect this?

```
NS="1 2 4 8 16 32 64 128 256 512 1024"; # What to measure over
for n in $NS; do
    echo $n;
    /usr/bin/time -f %e cat /dev/zero | head -c 1024000 | ./passthrough $n > /dev/null
done
```

**Comment by darioml** [comment] 2015-02-04 19:29
Also, am I the only one to see "Command terminated abnormally."? I see this also with the original passthrough file... @txsl

**Comment by m8pple** [comment] 2015-02-05 09:49
@darioml Thanks for the PR. I was in two minds about whether to update, as it is good for
people to realise that work rarely factors into exactly the right size chunks (comes up with
parallel for loops and OpenCL workgroups), but it's probably better at this stage to remove
barriers to completion.

Re "Command terminated abnormally", I haven't seen and wouldn't expect that, especially
on the original passthrough.c. As far as I'm aware that should be correct on all platforms.

It usually suggests there is a segfault somewhere, in this case probably related to overruns
of the buffer. x86 stack grows downwards, so if you overrun the buffer you often only
find out when it tries to unwind the stack (on function return). Does it occur during processing
of the stream, or only afterwards?

**Comment by m8pple** [comment] 2015-02-06 13:21
Closing for neatness.

**Closed as completed by m8pple** 2015-02-06 13:21 UTC
